### ISSUE TITLE
Fix Performance-data for Icinga2 

### ISSUE THREAD

**Issue by pgress** [aleex42/netapp-cdot-nagios#13]
Hi,
the volume-check can send performance-data as well, but the function doesn't work in the right way. There is only 1 Pipe-Symbol "|" allowed. Bit with "--perf" there are plenty of them. Maybe you can have a look at it.
Thanks and regards,
pgress

**Comment by pgress** [comment]
Here are some rules: https://docs.icinga.com/latest/en/perfdata.html#formatperfdata

**Comment by aleex42** [comment]
Seems only to affect volume check ...

**Comment by aleex42** [comment]
And surprise: was already fixed in Commit https://github.com/aleex42/netapp-cdot-nagios/commit/eca7a543e5b8112ae4bc0ca099a5a71b69c26673#diff-95fb6e5ef47f6e9b7060cdec7d0cfe44

Now fixed "Bytes" to "B" - now seems to work with Icinga :)
