### ISSUE TITLE
Use of uninitialized value 

### ISSUE THREAD

**Issue by chrkli193** [aleex42/netapp-cdot-nagios#16]
Hello,

I get the following plugin output but I don't know why. This only happens on one cdot-node

Use of uninitialized value $state in string ne at /usr/lib/nagios/plugins/netapp-cdot-nagios/check_cdot_interfaces.pl line 126.
Use of uninitialized value $state in string ne at /usr/lib/nagios/plugins/netapp-cdot-nagios/check_cdot_interfaces.pl line 126.
OK: All IFGRP fully active

I don't know why this happens.
cdot Version is 8.3.2P1. All other clusters have a newer release. Maybe that's the reason

Maybe you can help me with that output.
Thanks
Greetings

**Comment by aleex42** [comment]
Sorry for late reply - can you retry the skript?

I think the error now comes in line 127 or?
