### ISSUE TITLE
check_cdot_snapmirror.pl: Use of uninitialized value $current_transfer 

### ISSUE THREAD

**Issue by cguadall** [aleex42/netapp-cdot-nagios#17]
Command and output "anonymized". ONTAP 8.3.2P6, snapmirror status quiesced

# ./check_cdot_snapmirror.pl --hostname <ip> --username <user>  --password <passwd>
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
Use of uninitialized value $current_transfer in string ne at ./check_cdot_snapmirror.pl line 73.
CRITICAL: 9 snapmirror(s) failed - 11 snapmirror(s) ok
Name                          Healthy     Delay
SVM_iSCSI_XXX_mirror          false   184707s
SVM_iSCSI_XXX_mirror          false   184707s
SVM_iSCSI_XXX_mirror          false   184707s
SVM_CIFS_XXX_mirror           false   184707s
SVM_iSCSI_XXX_mirror          false   184707s
SVM_iSCSI_XXX_mirror          false   184707s
SVM_iSCSI_XXX_mirror          false   184707s
SVM_NFS_XXX_mirror            false   184707s
SVM_iSCSI_XXX_mirror          false   184707s

**Comment by aleex42** [comment]
Sorry for late response.

Can you retry the current skript? I think the error is in line 98?

Regards,
Alex
