### ISSUE TITLE
[check_cdot_wrong_aggregate.pl] WT...?

### ISSUE THREAD

**Issue by aramilialon** [aleex42/netapp-cdot-nagios#29]
I've just looked into the source code of the script since it was giving me an error regarding the DP volumes and I couldn't understand why and...
Why is the check looking into the aggregate name for the string "ata"? Isn't it probably better to check what type the aggregate is and filter it via parameter?
If it is better, let me work on it.

BR,

Giorgio

**Comment by aleex42** [comment]
There is no type for a dedicated snapmirror aggregate. 

At the moment no other idea how to fix this :(
