### ISSUE TITLE
embedded perl interpreter

### ISSUE THREAD

**Issue by banholzer** [aleex42/netapp-cdot-nagios#3]
script(s) didn't work out of the box on an Ubuntu 14.04 machine.
Did work when i ran the check_cdot_aggregates.pl in bash but didn't when nagios ran it with its epn
I don't know hot to fix the code or if this is based on code coming from the NetApp manageability-sdk.
What helped was adding a line "# nagios: -epn" to the top of the script.
I didn't use github so far. Should I patch the scripts with this line and create a pull request?

Used NetApp SDK / API 5.4

**Comment by aleex42** [comment]
Yes, just create a pull request :-)

**Comment by aleex42** [comment]
Seems to be fixed, or?
