### ISSUE TITLE
Dumper Undefined

### ISSUE THREAD

**Issue by rayholtz** [aleex42/netapp-cdot-nagios#34]
I ran check_cdot_clusterlinks.pl and received the following error:

`user@server1:/usr/lib/nagios/plugins$ ./check_cdot_clusterlinks.pl --hostname netapp --username monitoruser --password pw
Undefined subroutine &main::Dumper called at ./check_cdot_clusterlinks.pl line 117.`

after a little digging and a hint from http://www.perlmonks.org/bare/?node_id=430132 I added

`use Data::Dumper;`

after the other use statements, and it corrected the issue:

`user@server1:/usr/lib/nagios/plugins$ ./check_cdot_clusterlinks.pl --hostname netapp --username monitoruser --password pw
OK: all clusterlinks up`

Should the Data::Dumper be included there, or is there something wrong somewhere else in my install?

**Comment by aleex42** [comment]
I think I forgot to remove the dumper After debugging ;-)

I‘ll fix that tomorrow - thanks ;-)

**Comment by rayholtz** [comment]
Wow thats quick.  I'll check back in a couple days for an updated file.
Thanks @aleex42!

**Comment by aleex42** [comment]
Fixed :)

**Comment by rayholtz** [comment]
I replaced the file and it works great.  Thanks @aleex42 !!
