### ISSUE TITLE
Perfdata ouput of check_cdot_volume contains script name

### ISSUE THREAD

**Issue by log1-c** [aleex42/netapp-cdot-nagios#39]
Hi,

I`d like to ask what's the reason that the performance data output contains the script name, surrounded by "::"? 
Example:
Vol_vSphere/vol_vSphere_nfs_01::check_cdot_volume_usage::space_used
Vol_block/block_ROOT::check_cdot_volume_usage::space_used

This makes creating graphs from the performance data a bit uncomfortable.
Graphite seems to escape this nicely:
![image](https://user-images.githubusercontent.com/24474580/53170348-33d42b80-35e0-11e9-98d7-177d6e51c9c2.png)

But pnp4nagios has its problems. Though I didn't dive into it, to know why there are no pnp graphs for this check.

Best regards and thanks for the great plugins!

**Comment by aleex42** [comment]
Since I'm not using pnp4nagios or graphite, I don't know exactly.

If noone has any ideas, we can remove that in a few days :-)

**Comment by Tontonitch** [comment]
This format is based on check_multi, and works well in pnp.

![image](https://user-images.githubusercontent.com/600025/53172402-882dda00-35e5-11e9-9421-1a65c37aee37.png)

Could you tell me what your problem is?

**Comment by log1-c** [comment]
> Could you tell me what your problem is?
Thanks for the screenshot. Graphs are there, but I missed them.

And tbh that is quite a clean approach thinking about it now.
For graphite you have a bit of work to do, as you have to create a new template for this check, as the default does not work due to the "extra" scripts name. I just created one which works fine now. Took me an hour to figure it out :)

I'll close this issue, as I created it more out of confusion xD
Sorry for the hassle :)
