### ISSUE TITLE
check_cdot_disk.pl: wrong output for performance data

### ISSUE THREAD

**Issue by stevie-sy** [aleex42/netapp-cdot-nagios#43]
We are using check_cdot_disk.pl for monitoring our NetApp. We saw in the icinga2 log files, that there is a problem with the performance Output to the InfluxWriter:
![image](https://user-images.githubusercontent.com/38723488/56637045-f2590e80-666a-11e9-844d-ee37a65536c6.png)
In Icingaweb2 is this the output:
![image](https://user-images.githubusercontent.com/38723488/56637074-01d85780-666b-11e9-9757-2a84f4f9ddc9.png)

Taking a look into the [guidlines from Monitoring plugins](https://www.monitoring-plugins.org/doc/guidelines.html) I saw that 'Disks' is not an official UOM. So I think that's why the error exists and the output is wrong.

**Comment by log1-c** [comment]
Created a PR for this: https://github.com/aleex42/netapp-cdot-nagios/pull/45

**Comment by stevie-sy** [comment]
@log1-c thanks for that
