### ISSUE TITLE
check_cdot_multipath - Can't call method "child_get" on an undefined value

### ISSUE THREAD

**Issue by milo** [aleex42/netapp-cdot-nagios#47]
Hi,
thank you for your scripts! We run it on ONTAP 9.6 with netapp-manageability-sdk-9.4 and on master branch (2ac4070efa81923139bc389e8e2a3b6af7b1f0d4) we get following error:

```
# check_cdot_multipath.pl --hostname 123.123.123.123 -u nagios -p **********
Can't call method "child_get" on an undefined value at /usr/local/bin/nagios/netapp/netapp-cdot-nagios/check_cdot_multipath.pl line 51.
```
If I can provide some debug output, please, let me know how.

**Comment by aleex42** [comment]
Hey,

first of all: please upgrade the netapp-manageability-sdk to 9.6 oder 9.7

It must always be greater or equal to the ONTAP you are running.

If the error still exists then, please write again for further debugging.

Regards,
Alex

**Comment by milo** [comment]
Upgraded to `netapp-manageability-sdk-9.7` and got the same error.

I found that the error arise only with a wrong password. With correct one, I get `OK: All disks multipath` so this is probably a cosmetic issue only.

**Comment by aleex42** [comment]
Fixed in https://github.com/aleex42/netapp-cdot-nagios/commit/186e9d08da5cbcc3512527b32fe0752ba921caeb

Will do this in all other checks, too :-)

Thanks!

**Comment by milo** [comment]
Nice, thank you :) And verified that it works.
