### ISSUE TITLE
How to access NetApp

### ISSUE THREAD

**Issue by ShowMeYourSkil** [aleex42/netapp-cdot-nagios#61]
Hi,

I am asking myself the following question: How do they access the information from the NetApp? 
Do you use a normal SNMP query?

**Comment by log1-c** [comment]
The checks are using the NetApp Manageability Perl SDK to query the API. No SNMP used in any of the scripts from this repo.

**Comment by log1-c** [comment]
Yes.
I recommend creating a monitoring user, if I remember correctly the user just needs one permission to access the HTTP API.

**Comment by ShowMeYourSkil** [comment]
Thank you for your support, I have created my user with the SSH command `secure login create` and given the role `read-only`.
